[package]
name = "steam-dl-inhibit"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
dbus = "0.9.9"
inotify = "0.11.0"
serde = { version = "1.0.228", features = ["derive"] }
vdf-reader = "0.3.1"
